language: node_js
script: npm run test
notifications:
  email: false
  slack:
    rooms:
      secure: VkxszGO6+CUvoemP0KXYOWT8Orqkkl0O+MlS/BJ6Lk8O3MsfpI7FI8qe61THJ/EA5uZwshu5PldOXQe7dV8lv631AI6AcTvywLcm/wCjjimH9//NL8VyBDrkMVvR9PzB9mygnuQIuWhGhxY2sJXFGCMdj0ZqVY5T2LaVX1WjxD18l/LlNcYf8aPI0Zed1XBUrT+eVPyJyexCGQ5B5aLXc0+h1uLMx0pQlM6O4NrslGm2lIW3yiLW+RnzzngWMSrcZfJWsL9vlzYJ38Ud7FfEE9Z1Y6tQsG+Uq7gJ+vd0FgEeGYBUf/MBsleX0dpKpw5cReF8UCG5FaE6LRoio0Cpu/pFGWh2hfuhwGbmUT7q5ch7DJ8BQpSciazUHZAEsXeXf/K+bWcqlRx0ViAun9oFAOSeKE92GPPhLG9cGARJF+57zhtyPG7qzbN8B7np7AeEtdJlahzy9+OCvfmU5KgvxHFD2+7c2oZbcEKkok1iIbLRswQR0++4HxQrCzkRJCCzHQ5qYIyOKulyotV6xbrgZTIS8fonfSPaqCHJ9fxJIUe7jih6wjUV007pjIUe35oHOtc9fcIcT3sEmvrP1xqkiXpY7J5eU+GyzmrwbynEG+bCGsfbjvoZvgVKqg1fcIjwF2oFA5tmhggh+vhJcvjU/aoVN4eSKq6OAfmkzCPitx0=
