language: node_js
script: npm run test
notifications:
  email: false
  slack:
    secure: htJT9O+bXILXZOnup1Z3zVAIbOsa+ji+jnEVDL+QEkDDPa1672aCvbQMGX/JjFut64iXXhjkCJ8cWImTStpzLBgzb4oth63R3cA0sMsS2oSBs8gGqhBCFllJd1poyVxkS34NyUrRKmSXSYgnc9YEH2OdKHlzPj8b6L1H599UPToKwXGWyItz0xahxTypDNbhmY1GXr46L9uu7wyoHgBvZuJBwaewLX9+O8C8SFW60pvTYj+VGuASr+DDI3+00Qmv58/cVSSVrbMT3a2Weg68wkeiPLokOSECBQLkQuJtKU39ZNi+exvj26EM4rq1e+KdqFMelr4gaoeeRSAG9TgMPA3CZ7L4pNt8B2W943vsnEdVuFzDDw/RPP7R2phq24M5uZT7UTgNbq09U0MBLqJczD8d9hZeXzdGWSfJna5ptVTNLpeA5vyZWY96IWADu7qT+sHDSxe9H/5CBl25N33SgXQGom5jbjCW1eWNIqbYS/GJWIhcpkPJcgBSdR3xk1WtpNVjNt4y1dsbFB4ACWc/KdM67am4WHtTQOp+FUSs6iMdEvJTk+nbxSu18WgyQuHC+y0VlqrmuFsJYeFedReOTcH9WrYwB/ITPhMBmiCXEAH1nHovBVGRnLt6jQcydpg6S08ol8E5bTd5HGdglqKyqD8Es2OALTfh/enjAwmGLRY=
